### ISSUE TITLE
Add view for viewing sql (that also uses content from include elements)

### ISSUE THREAD

**Issue by atsu85** [harawata/mybatipse#28]
Add view for viewing sql (that also uses content from include elements).

This functionality is already implemented in MyBatis Editor and i got the permission (from Peter Hendriks - the owner of https://code.google.com/a/eclipselabs.org/p/mybatiseditor/issues/detail?id=9 ) to port it into this project.

See https://code.google.com/a/eclipselabs.org/p/mybatiseditor/#Introduction

**Comment by harawata** [comment]
Hi,

I am going to implement it as a text hover instead of the separate view.

By moving the mouse cursor over a statement id, the small yellow window appears with the sql statement.
You can, of course, select and copy the text into the clipboard.

![captur_3](https://cloud.githubusercontent.com/assets/149268/5831612/3718f1cc-a179-11e4-9e8e-a262dddf5e9e.png)

If you think this does not provide what you want, please let me know some example usage.
Thank you!

**Comment by atsu85** [comment]
Hi,
This sounds like a really good addition, but I'd really like to have an option to use thew view as well. I understand the benefit of not needing to switch to separate view every time you want to see a small sql. But it seems to me that with large sql's it would really be better to have an option to open standalone view.

What do You think?

**Comment by harawata** [comment]
When the statement is large, you can enlarge the hover window.
I am not sure how often you will use this feature, but the hover window seems to be a better fit for displaying a static text.

![captur_4](https://cloud.githubusercontent.com/assets/149268/5843221/461778f4-a1ee-11e4-9ba9-811c696267c3.png)

Why don't you try using the hover for a while and see if it works or not?
If you really can't work with hover, I will reimplement it as a separate view (I don't like applications with many options ;-) ).

**Comment by harawata** [comment]
I woke up and changed my mind.
It will be implemented as the separate view and included in the next version.
Thanks again for your work and comments!
